Add endpoint
stackbuilders/nano-chat pull request #5
Opened 2018-07-20 19:07 UTC by JoseLion

- Organized the app so the file ./bin/www.js sets up an begins the listening of the server (use this file to run the app)
- Added sequelize and a connection to the database (it can be accessed with: `import sequelizeConn from 'Core/sequelizeConn';`)
- Added a 'User' model (it can be accessed with: `import User from 'Models/User';`)
- Added sequelize migrations and seeders
- Added an endpoint which return all users in database (/api/users)
- Added a function which add a test user programmatically (uncomment line 11 of ./src/app.js)
- Added BabelJS as transpiler so some other ES6 features are available (import and export specially)
- Added babel-module-resolver to create alias to folders for imports (improves coding organization and prevents from typing large absolute paths several times)

2018-07-20 19:16 UTC, po5i commented on backend/src/app.js
> +app.get('/api/users', async (request, response) => {
Can you add how to test this endpoint to the README?

2018-07-20 21:18 UTC, po5i requested changes

2018-07-20 21:18 UTC, po5i commented on backend/bin/www.js
> +if (!process.env.DB_CONN_NANOCHAT) {
As discussed, please document all the necessary steps to start the server locally

2018-07-25 14:55 UTC, po5i approved these changes
LGTM 🎉 🚢

2018-08-02 21:16 UTC, sestrella approved these changes
@JoseLion LGTM nice job!

2018-08-02 21:48 UTC, merged